### ISSUE TITLE
Blue line is coming inside SQTextEditorView

### ISSUE THREAD

**Issue by Saranjithpk** [OneupNetwork/SQRichTextEditor#1]
Below given screenshot of custom SQRichTextView. It has some blue line at bottom, How to remove this?

<img width="214" alt="Screenshot 2020-03-01 at 5 54 28 PM" src="https://user-images.githubusercontent.com/37569412/75625619-e2448080-5be5-11ea-82a4-c2bc29f3335d.png">

**Comment by conscientiousness** [comment]
I have fixed this issue. You can try it again. Thank you.
